name: Build & Deploy to GitHub Pages

# Trigger on pushes to your default branch (e.g. main) or manual runs
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # for checkout
      pages: write         # for deploy-pages
      id-token: write      # for authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'       # or 20 if you prefer

      - name: Install dependencies
        run: npm ci

      - name: Build site with Astro
        run: npm run build        # outputs to ./dist by default

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
